apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: opentelemetry
    component: prometheus
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: prometheus
  template:
    metadata:
      labels:
        app: opentelemetry
        component: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus-config.yaml
            - --web.enable-remote-write-receiver
            - --enable-feature=exemplar-storage
          volumeMounts:
            - name: prometheus-config-vol
              mountPath: /etc/prometheus/
          ports:
            - containerPort: 9090
      volumes:
        - configMap:
            defaultMode: 420
            name: prometheus-conf
          name: prometheus-config-vol
          