---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: opentelemetry
    component: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    component: prometheus