global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: collector
    scrape_interval: 5s  # How frequently to scrape targets by default.
    static_configs:
      - targets: [ 'collector:8889' ]  # List of labeled statically configured targets for this job.

  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]


  