
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    httpMethod: GET
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: tempo

- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    derivedFields:
      - name: TraceID
        datasourceUid: tempo
        matcherRegex: (?:traceID|trace_id)=(\w+)
        url: $${__value.raw}

- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    tracesToLogs:
      datasourceUid: loki
      tags: ['job', 'instance', 'pod', 'namespace']
    serviceMap:
      datasourceUid: prometheus
  # jsonData:
  #   httpMethod: GET
  #   serviceMap:
  #     datasourceUid: prometheus
# - name: Tempo
#   type: tempo
#   uid: tempo
#   url: http://tempo/
#   access: proxy
#   editable: true
#   isDefault: false
#   jsonData:
#     httpMethod: GET
#     tracesToLogs:
#       datasourceUid: 'loki'
#       tags: ['job', 'instance', 'pod', 'namespace']
#   version: 1