apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kbot
  name: kbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kbot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/otel-default: "true"
        io.kompose.service: kbot
    spec:
      containers:
        - env:
            - name: METRICS_HOST
              value: collector:4317
            - name: TELE_TOKEN
              value: ${TELE_TOKEN}
          image: denvasyliev/kbot:v1.0.0-otel
          name: kbot
          resources: {}
      restartPolicy: Always
status: {}
