image:
  repository: ghcr.io/ibra86
  tag: v1.1.0-8e355f5
  os: linux
  arch: amd64
secret:
  env: TELE_TOKEN
  key: token
  name: kbot
autoscaling:
  enabled: false
replicaCount: 1
service:
  port: 80
