# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ibra86
  tag: "v1.0.6-583901b"
  arch: amd64
secret:
  name: kbot
  env: TELE_TOKEN
  key: token
securityContext:
  priviledged: true
