image:
  repository: ghcr.io/ibra86 
  tag: v1.0.10-9801631
  os: linux
  arch: amd64
secret:
  env: TELE_TOKEN
  key: token
  name: kbot
autoscaling:
  enabled: false
replicaCount: 1
service:
  port: 80
