image:
  repository: ibra86dspl  #ghcr.io/ibra86
  tag: v1.1.0-5ccad31
  os: linux
  arch: amd64
secret:
  env: TELE_TOKEN
  key: token
  name: kbot
autoscaling:
  enabled: false
replicaCount: 1
service:
  port: 80
