name: KBOT-CICD

on: push

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTATINER_REGISTRY_USERNAME: ibra86

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run simple make check
        run: make check

      - name: Run env vars make check
        env:
          APP: kbot
          REGISTRY: ${{env.CONTAINER_REGISTRY}}/${{env.CONTATINER_REGISTRY_USERNAME}}
        run: make check

      - name: Run passed params make check
        run: make check REGISTRY=${{env.CONTAINER_REGISTRY}}/${{env.CONTATINER_REGISTRY_USERNAME}}
