name: KBOT-CICD

on: push

env:
  GITHUB_PROJECT: k8s-k3s-386219
  GCP_KEYRING: sops-flux-2
  GCP_KEYRING_KEY: sops-key-flux
  KMS_CRYPTO_KEY: projects/k8s-k3s-386219/locations/global/keyRings/sops-flux-2/cryptoKeys/sops-key-flux
  WORKLOAD_IDENTITY_PROVIDER: projects/309987332695/locations/global/workloadIdentityPools/sops-pool-2/providers/sops-wip-provider-2
  SERVICE_ACCOUNT: github-actions-sa-2@k8s-k3s-386219.iam.gserviceaccount.com
  FLUX_REPO: ibra86/flux-sops-gitops

jobs:
  sops:
    name: sops
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions for google service account.
    permissions:
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{env.WORKLOAD_IDENTITY_PROVIDER}}
        service_account: ${{env.SERVICE_ACCOUNT}}

    - name: clone-flux-repo
      uses: actions/checkout@v3
      with:
        repository: ${{env.FLUX_REPO}}
        token: ${{secrets.ACCESS_TOKEN}}
        path: flux-repo
        ref: main

    # - name: test-secret
    #   run: |
    #     cd flux-repo/
    #     ls -lsa
    #     cp ../helm/secret-template.yaml clusters/demo/
    #     cd clusters/demo
    #     ls -lsa

    - name: install-sops
      run: |
        curl -O -L -C - https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux
        sudo mv sops-v3.7.3.linux /usr/bin/sops
        sudo chmod +x /usr/bin/sops

    - name: yq 
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.data.token="${{env.TELE_TOKEN}}"' helm/secret-template.yaml

    - name: 'sops-ecnrypt'
      run: |
        cat helm/secret-template.yaml
        cat helm/secret-template.yaml | sops -e -gcp-kms ${{env.KMS_CRYPTO_KEY}} --encrypted-regex '^(token)$' --input-type yaml --output-type yaml /dev/stdin > helm/secret.yaml

    - name: push-secret
      run: |
        cd flux-repo/
        cp ../helm/secret.yaml clusters/demo/
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add clusters/demo/secret.yaml
        git commit -m "secret-template.yaml"
        git push
