apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
        - args:
            - "--config=/etc/otel/otel-collector-config.yaml"
          image: otel/opentelemetry-collector-contrib:0.78.0
          name: otel-collector
          ports:
            - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
            - containerPort: 8889 # Default endpoint for querying metrics.
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /etc/otel/
      volumes:
        - configMap:
            defaultMode: 420
            name: otel-collector-conf
          name: otel-collector-config-vol
