apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: otel-collector-conf
    files:
      - otel-collector-config.yaml
